### ISSUE TITLE
Magic Query Row error/exception on certain queries

### ISSUE THREAD

**Issue by dalibert42** [thecodingmachine/magic-query#28]
When supplying some queries to a MagicQueryRow, these error/exception occure:

SELECT ee.`data`, Substring_index(REPLACE(Substring_index(ee.`data`, ':', -1), '"}', ''), '"', -1) AS 'Motif'
FROM   `entity` e
       LEFT JOIN `event_entity` ee
              ON ee.`entity_id` = e.`id`
WHERE  e.`id` = :identifier

![mqr_error_parsing](https://cloud.githubusercontent.com/assets/19168056/16145915/9dbd247a-347b-11e6-8f45-0b53e5980bdf.JPG)

SELECT ee.`data`, Substring_index(REPLACE(Substring_index(ee.`data`, ':', '-1'), '"}', ''), '"', '-1') AS 'Motif'
FROM   `entity` e
       LEFT JOIN `event_entity` ee
              ON ee.`entity_id` = e.`id`
WHERE  e.`id` = :identifier

![mqr_syntaxerrorexception](https://cloud.githubusercontent.com/assets/19168056/16145939/b9b36efa-347b-11e6-826c-4f8c3f7481f5.JPG)

But everything work fine on a query like this one:

_SELECT ee.`data`, Substring_index(REPLACE(Substring_index(ee.data, ':', '-1'), CHAR(34, 125), ''), CHAR(34), '-1') AS 'Motif' 
FROM   `entity` e 
       LEFT JOIN `event_entity` ee 
              ON ee.`entity_id` = e.`id` 
WHERE  e.`id` = :identifier_

**Comment by moufmouf** [comment]
This is due to a poor parsing of the SQL done by the old version of SQLParser that I bundled with MagicQuery a few years ago (at the time, there was no composer package for PHPSQLParser).

The new PHPSQLParser version seems to solve this. I'll try to migrate to it:

https://github.com/greenlion/PHP-SQL-Parser

**Comment by moufmouf** [comment]
Ok, the new PHPSQLParser does not solve the issue BUT I opened a pull request for it:

https://github.com/greenlion/PHP-SQL-Parser/pull/202

I'll be migrating to greenlion/PHP-SQL-Parser soon.

**Comment by moufmouf** [comment]
And it's merged, therefore, solved in magic-query 1.2.

yeah!
